from __future__ import annotations

from typing import Annotated, Dict, List, Optional, TypedDict

from pydantic import BaseModel


def dict_reducer(a: Optional[dict], b: Optional[dict]) -> dict:
    """Reduce a dictionary using keys to merge the values."""
    if a is None:
        a = {}
    if b is not None:
        a.update(b)
    return a


class InputState(BaseModel):
    """Main input state."""

    job_description: str
    experience_ids: List[int]


class OutputState(BaseModel):
    """Main output state."""

    cover_letter: str | None = None
    """The cover letter."""

    resume: str | None = None
    """Deprecated: The resume text. Prefer `resume_text`."""

    resume_text: str | None = None
    """The resume text generated by the resume sub-agent."""

    resume_pdf_path: str | None = None
    """Filesystem path to the generated resume PDF."""

    linkedin_message: str | None = None
    """The LinkedIn message."""

    hr_manager_message: str | None = None
    """The HR manager message."""

    hiring_manager_message: str | None = None
    """The hiring manager message."""


class InternalState(InputState, OutputState, BaseModel):
    """State."""

    current_experience_id: int | None = None
    """The identifier of the current experience being processed."""

    job_title: str | None = None
    """The extracted job title from the job description."""

    job_requirements: Dict[int, str] = {}
    """Extracted job requirements."""

    summarized_experience: Annotated[Dict[str, List[Summary]], dict_reducer] = {}
    """Summarized experience. The key is the title of the experience."""

    summarized_responses: Annotated[Dict[str, List[Summary]], dict_reducer] = {}
    """Summarized responses. The key is the source of the responses."""

    cover_letter_feedback: str | None = None
    """Feedback for the cover letter."""


class Summary(BaseModel):
    """Summary of the experience."""

    requirements: List[int]
    """The requirements that the summary covers."""

    summary: str
    """The summary of the experience."""


class PartialInternalState(TypedDict, total=False):
    """Partial state for return types."""

    job_description: str | None
    experience_ids: List[int] | None
    current_experience_id: int | None
    job_title: str | None
    job_requirements: Dict[int, str] | None
    cover_letter: str | None
    resume: str | None
    resume_text: str | None
    resume_pdf_path: str | None
    linkedin_message: str | None
    hr_manager_message: str | None
    hiring_manager_message: str | None
    summarized_experience: Dict[str, List[Summary]] | None
    summarized_responses: Dict[str, List[Summary]] | None
    cover_letter_feedback: str | None
